version: 2

models:
  - name: dim_hotels
    columns:

      - name: PROPERTY_ID
        tests:
          - unique
          - not_null
  - name: fct_bookings
    columns:
    
      - name: REVENUE_REALIZED
        tests:
          - positive_value