version: 2

sources:
  - name: hoteldbt
    schema: raw
    tables:
      - name: bookings
        identifier: raw_bookings
        loaded_at_field: BOOKING_DATE
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}


      - name: hotels
        identifier: raw_hotels
      
      - name: rooms
        identifier: raw_rooms